---
title: "WIP"
author: "Emory Genecore"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(gencoreSC)
```

```{}
This script is intended to be a convenient way to load in data quickly for testing
new features. It uses some test data stored in a stable location
```


```{r}
# samplesheet <- read.table(here('config/samplesheet.txt'), header=TRUE)
# config <- yaml::yaml.load_file(here("config/scRNA_GEX_config.yml"))
samplesheet <- data.frame(FileID = c('capture_31', 'capture_32'),
                          Label = c('Cap31', 'Cap32'))
config <- list()
config$rootDir <- '/yerkes-cifs/runs'
config$alignmentDir <- 'tools/templates/example_data/sc_ADT+GEX+HTO'

```


```{r}
objs <- mapply(readCounts10x,
               samplesheet$Label,
               file.path(config$rootDir,
                         config$alignmentDir, 
                         samplesheet$FileID,
                         'outs/per_sample_outs/', 
                         samplesheet$FileID, 
                         'count/sample_feature_bc_matrix'),
               strip.suffix = FALSE,
               USE.NAMES = TRUE)
```

```{r}
objs <- lapply(objs, filterLowGenes, min.cells = 100, assay = 'RNA', calculate_only = FALSE)
objs <- lapply(objs,
              addQCmetrics,
              mito.pattern = "^MT", ## edit patterns as needed
              ribo.pattern = "^RP[SL]")
```

```{r}
cutoffs <- lapply(objs, generate_capture_QC_cutoffs)
objs <- mapply(addQCfilter, objs, 'outliers', cutoffs)
```

```{r, message=TRUE, warning=FALSE, fig.width=18, fig.height=15}
## Generate dashboard plots of filtering regimes
cell_filtering_plots <- list()
## if you added multiple filters, say one with default settings and one with
## modified thresholds, you can plot all of them here. Specifying 'input'
## shows the unfiltered cells in a separate dashboard
for (filtName in c('input', 'outliers')) {
  cell_filtering_plots[[filtName]] <- plotQCRidgesJoint(objs, 
                                              filtName = filtName,
                                              title = filtName, 
                                              split_by = "capID", 
                                              color_by = "riboRatio",
                                              cutoffs = cutoffs,
                                              facet_colors = TRUE)
}
cell_filtering_plots
```
