---
title: "WIP"
author: "Emory Genecore"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{}
this file holds some code that is a work in progress, and may be added to the main 
workflow later
```


# Trajectory inference

```{r}
library(slingshot)
sce <- as.SingleCellExperiment(combined.obj)
sce <- slingshot(sce, clusterLabels = 'seurat_clusters', reducedDim = 'UMAP')
test <- as.Seurat(sce)

dimred <- combined.obj@reductions$umap
clustering <- combined.obj$seurat_clusters
counts <- as.matrix(combined.obj@assays$RNA@counts[combined.obj@assays$RNA@var.features,])
lineages <- getLineages(data = dimred, clusterLabels = clustering)
```


```{r}
DimPlot(combined.obj, reduction = 'umap')
ssds <- SlingshotDataSet(sce)
pto <- as.PseudotimeOrdering(sce)
lines(SlingshotDataSet(sce))
```


## Most common features

Plotting highly expressed genes. We expect to see constitutively expressed genes (e.g. mitochondrial, ribosomal, etc).

```{r most_abundant_genes, fig.width=10, fig.height=4}
plot_top_genes <- function(data, n=20){
  C <- data@assays$RNA@counts
  C <- Matrix::t(Matrix::t(C)/Matrix::colSums(C)) * 100
  most_expressed <- order(apply(C, 1, median), decreasing = T)[20:1]
  par(mar=c(5,12,4,1)+.1)
  boxplot(as.matrix(t(C[most_expressed, ])), las=1, cex=0.1, xlab = "% total count per cell", col = (scales::hue_pal())(20)[20:1], horizontal = TRUE, main=data@project.name) 
}
tmp <- lapply(captures, plot_top_genes)
```



## Term enrichment

```{r}
library(clusterProfiler)
markers_res0.5 <- readRDS('wip/merged_markers_res0_5.rds')
markers_res0.1 <- readRDS('wip/merged_markers_res0_1.rds')
az_markers <- readRDS('wip/Azimuth_PBMC_Type2_Markers_List.rds') %>%
  melt() %>%
  select(L1, value)
colnames(az_markers) <- c('L1', 'V1')
#tcell_markers <- read.table('wip/Tcellmarkers.xlsx', header = FALSE)
```

```{r}

universe <- read.csv('wip/GeneList_p22128_Maura.csv', header=FALSE)
#az_markers <- rbind(az_markers, data.frame(L1='universe',universe))
```


```{r}
## BiocManager::install("clusterProfiler")
## library(clusterProfiler)
celltype_marker_enricher <- function(cluster_markers, celltype_markers,
                                     universe, ...){
  colnames(celltype_markers) <- c('L1', 'V1')
  celltype_markers <- rbind(celltype_markers, data.frame(L1='universe',V1=universe))
  enrichment_test <- enricher(cluster_markers, 
                              #universe = universe,
                              TERM2GENE = celltype_markers,
                              ...
                              )
  enrichment_test
}

## This function can be called by itself if you just have a single list of
## markers that you want to test. Based on your setup, you could pass in a 
## universe, or you could just pass the same list of markers as the universe
## for a quick look

cluster_enrichment_tests <- function(cluster_markers, celltype_markers,
                                     alpha=0.05, ...){
  enrich_results <- data.frame()
  cluster_markers$cluster <- as.character(cluster_markers$cluster)
  for (clus in unique(cluster_markers$cluster)){
    markers <- cluster_markers %>%
      filter(cluster == clus,
             avg_log2FC > 0,
             p_val_adj < alpha)
    markers <- markers$gene
    universe <- cluster_markers %>% 
      filter(cluster == clus) %>%
      pull(gene) %>% 
      unique()
    results <- celltype_marker_enricher(markers, celltype_markers, universe, ...)
    results <- results@result
    results$cluster <- clus 
    enrich_results <- rbind(enrich_results, results)
  }
  enrich_results
}

## cluster_markers : dataframe, result from FindAllMarkers call containing
##   all markers (run with return.thresh = 1)
## celltype_markers: two column dataframe, first column is set, second is gene
## e.g. 
##       L1      V1
## 1 B_cells SLC4A10
## 2 B_cells    GZMA
## 3 B_cells   CXCR6
## Additional arguments to enricher can be passed in via ...
## e.g. minGSSize will set the minumum size threshold for a set to be tested
# cluster_enrichment <- cluster_enrichment_tests(cluster_markers = markers_res0.1,
#                                                celltype_markers = az_markers,
#                                                minGSSize = 2)
```




```{r}
maura_markers <- read_rds('/Volumes/yerkes/genomelab/illumina/runs/Analysis/2022_Analyses/p22128_Maura/p22128_Maura_Analysis/Maura_Markers_v0.1.rds')

res0.1_maura_res <- cluster_enrichment_tests(cluster_markers = markers_res0.1, celltype_markers = maura_markers, minGSSize=2)
#rite_rds(test, 'enrichment_res0.1.rds')
res0.1_maura_res <- merge(res0.1_maura_res, melt(table(maura_markers$Cell.name)), by.x = 'ID', by.y = 'Var1') %>% 
  as.data.frame() %>% 
  mutate('Set_Size' = value, .keep = 'unused') %>% 
  arrange(cluster, pvalue)

res0.1_maura_res$Fraction_of_set_detected <- round(res0.1_maura_res$Count / res0.1_maura_res$Set_Size, 3)
#%>% select(Count, cluster, GeneRatio, BgRatio)
write_rds(res0.1_maura_res, 'maura_markers_enrichment_res0.1.rds')
res0.1_maura_res
```

```{r}
res0.5_maura_res <- cluster_enrichment_tests(cluster_markers = markers_res0.5, celltype_markers = maura_markers, minGSSize=2)
#rite_rds(test, 'enrichment_res0.1.rds')
res0.5_maura_res <- merge(res0.5_maura_res, melt(table(maura_markers$Cell.name)), by.x = 'ID', by.y = 'Var1') %>% 
  as.data.frame() %>% 
  mutate('Set_Size' = value, .keep = 'unused') %>% 
  arrange(cluster, pvalue)

res0.5_maura_res$Fraction_of_set_detected <- round(res0.5_maura_res$Count / res0.5_maura_res$Set_Size, 3)
#%>% select(Count, cluster, GeneRatio, BgRatio)
write_rds(res0.5_maura_res, 'maura_markers_enrichment_res0.5.rds')
res0.5_maura_res
```

```{r}
test1 <- cluster_enrichment_tests(cluster_markers = markers_res0.5, celltype_markers = az_markers, universe = universe[,1], minGSSize=2)

write_rds(test1, 'enrichment_res0.5.rds')

test1 %>% 
  dplyr::group_by(cluster) %>%
  slice_min(n=5, order_by = pvalue, with_ties = FALSE)
```

