# root dir is base of mounted file system, might change by machine
# The default should be appropriate for mounted systems
rootDir: '/yerkes-cifs/runs/Analysis/'
# cellranger counts output parent folder
alignmentDir: '../../tools/templates/example_data/sc_ADT+GEX+HTO'
